Move metastore locator plugin access out of the constructor to ensure…
pentaho/pentaho-hadoop-shims pull request #1360
Opened 2023-04-20 19:17 UTC by urena-kenny

… it isn't used before the plugin is loaded. Added 'synchronized'

2023-04-20 19:24 UTC, abryant-hv approved these changes

2023-04-20 19:38 UTC, buildguy commented
### :white_check_mark: Build finished in 20m 31s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl common-services-api
```
---
:ok_hand: All tests passed!
 
Tests run: **796**, Failures: **0**, Skipped: **2** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-hadoop-shims/job/PR-1360/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-04-20 19:42 UTC, peterrinehart approved these changes

2023-04-20 20:29 UTC, peterrinehart requested changes
Forgot the jira ticket tag in the commit message.  Ok otherwise.

2023-04-21 14:26 UTC, buildguy commented
### :white_check_mark: Build finished in 16m 32s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl common-services-api
```
---
:ok_hand: All tests passed!
 
Tests run: **796**, Failures: **0**, Skipped: **2** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-hadoop-shims/job/PR-1360/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-04-21 14:53 UTC, peterrinehart approved these changes

2023-04-21 19:29 UTC, ddiroma approved these changes

2023-04-21 19:30 UTC, merged